=== notianx/BedRockModMakerFramework/boot/buildScripts/templates/mainProjectTemplate/beh/item/dtd/item.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT item (beh, res)>

<!ELEMENT beh (ID, name, tab, maxSize, foil, isCreateModeShow)>
<!ELEMENT ID ANY>
<!ELEMENT name ANY>
<!ELEMENT tab ANY>
<!ELEMENT maxSize ANY>
<!ELEMENT foil ANY>
<!ELEMENT isCreateModeShow ANY>

<!ELEMENT res (textures)>
<!ELEMENT textures ANY>

<!ATTLIST item type CDATA "">

=== notianx/BedRockModMakerFramework/boot/buildScripts/templates/mainProjectTemplate/beh/item/prop/item.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE item SYSTEM "../dtd/item.dtd">

<item type="prop">

    <beh>
        <ID>item</ID>
        <name>物品</name>
        <tab>tab</tab>
        <maxSize>32</maxSize>
        <foil>false</foil>
        <isCreateModeShow>true</isCreateModeShow>
    </beh>

    <res>
        <textures>None</textures>
    </res>

</item>
