=== notianx/BedRockModMakerFramework/boot/buildScripts/templates/mainProjectTemplate/beh/item/dtd/weapon.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT item (beh, res)>

<!ELEMENT beh (ID, name, tab, foil, isCreateModeShow, damage)>
<!ELEMENT ID ANY>
<!ELEMENT name ANY>
<!ELEMENT tab ANY>
<!ELEMENT foil ANY>
<!ELEMENT isCreateModeShow ANY>
<!ELEMENT damage ANY>

<!ELEMENT res (textures)>
<!ELEMENT textures ANY>

<!ATTLIST item type CDATA "">

=== notianx/BedRockModMakerFramework/boot/buildScripts/templates/mainProjectTemplate/beh/item/weapon/weapon.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE item SYSTEM "../dtd/weapon.dtd">

<item type = "weapon">

    <beh>
        <ID>weapon</ID>
        <name>烈焰之剑</name>
        <tab>tab</tab>
        <foil>false</foil>
        <isCreateModeShow>true</isCreateModeShow>
        <damage>5</damage>
    </beh>

    <res>
        <textures>None</textures>
    </res>

</item>
