=== notianx/BedRockModMakerFramework/boot/buildScripts/templates/mainProjectTemplate/beh/block/dtd/block.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT block (beh, res, monster_box*)>

<!ELEMENT beh (ID, name, isCreateModeShow, light)>
<!ELEMENT ID ANY>
<!ELEMENT name ANY>
<!ELEMENT isCreateModeShow ANY>
<!ELEMENT light ANY>

<!ELEMENT monster_box (monster)>
<!ELEMENT monster ANY>

<!ELEMENT res (textures)>
<!ELEMENT textures ANY>

<!ATTLIST entity type CDATA "">

=== notianx/BedRockModMakerFramework/boot/buildScripts/templates/mainProjectTemplate/beh/block/block.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE block SYSTEM "../block/dtd/block.dtd">

<block>

    <beh>
        <ID>testB</ID>
        <name>测试方块</name>
        <isCreateModeShow>true</isCreateModeShow>
        <light>0</light>
    </beh>

    <res>
        <textures>textures/blocks/testB</textures>
    </res>

</block>
